/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.company.utils;

import org.company.utils.internal.StringUtilsHelper;

import java.time.Instant;

public class StringUtils {
    private final Instant created = Instant.now();

    public String greet(String name) {
        return new StringUtilsHelper().prepareGreeting(name);
    }
//    public StringUtils() {
////        throw new Exception("'cause why not?");
//    }

    public void publicMethod() {
        System.out.println("public method called");
    }

    private void privateMethod() {
        System.out.println("private method called");
    }

    @Override
    public String toString() {
        return "String Utils which was created at: " + created;
    }
}
